export { default as BadgeApple} from "./badge-apple.svg";
export { default as WarningIcon} from "./original/Contoso_Assets/Icons/information_icon.svg"
export { default as Electrical } from "./home_electrical.jpg";
export { default as Garden } from "./home_gardencenter.jpg";
export { default as Plumbing } from "./home_plumbing.jpg";
export { default as Powertools } from "./home_powertools.jpg";
export { default as LaptopGirl} from "./original/Contoso_Assets/Grid_Products_Collection/banner_1.jpg";
export { default as LaptopPic} from "./original/Contoso_Assets/Grid_Products_Collection/product_image.png";
export { default as HeroBG } from "./original/Contoso_Assets/Slider_section/hero_banner.jpg";
export { default as HeroBG2 } from "./original/Contoso_Assets/Slider_section/hero_banner-2.jpg";
export { default as LocalMallIcon } from "./original/Contoso_Assets/Icons/cart-icon-copy.svg";
export { default as Logo } from "./logo-horizontal.svg";
export { default as BagIcon } from "./original/Contoso_Assets/Icons/cart_icon.svg";
export { default as SearchIconNew } from "./original/Contoso_Assets/Icons/image_search_icon.svg";
export { default as ProfileIcon } from "./original/Contoso_Assets/Icons/profile_icon.svg";
export { default as LogoutIcon } from "./original/Contoso_Assets/profile_page_assets/logout_icon.svg";
export { default as PersonalInformationIcon } from "./original/Contoso_Assets/profile_page_assets/personal_information_icon.svg";
export { default as LogoHorizontal } from "./logo-horizontal.svg";
export { default as PhoneLogo } from"./original/Contoso_Assets/Icons/telephone_icon.svg";
export { default as EmailLogo } from "./original/Contoso_Assets/Icons/email_icon.svg";

export { default as CloseIcon } from "./icon-close.svg";
export { default as ControllersIcon } from "./original/Contoso_Assets/Mega_menu_dropdown_assets/controllers_icon.svg";
export { default as DesktopsIcon } from "./original/Contoso_Assets/Mega_menu_dropdown_assets/desktops_icon.svg";
export { default as LaptopsIcon } from "./original/Contoso_Assets/Mega_menu_dropdown_assets/laptop_icon.svg";
export { default as MobilesIcon } from "./original/Contoso_Assets/Mega_menu_dropdown_assets/mobiles_icon.svg";
export { default as MonitorIcon } from "./original/Contoso_Assets/Mega_menu_dropdown_assets/monitor_icon.svg";
export { default as OfferBanner} from "./original/Contoso_Assets/product_page_assets/collection_page_banner.jpg";
export {default as AddToBagIcon} from "./original/Contoso_Assets/product_page_assets/add_to_bag_icon.svg";
export {default as DiscountImage}  from "./original/Contoso_Assets/product_page_assets/discount.png";
